# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: productos.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'productos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproductos.proto\x12\x08\x66\x65rremas\x1a\x1bgoogle/protobuf/empty.proto\"Y\n\x08Producto\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05marca\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x02\x12\x0e\n\x06imagen\x18\x05 \x01(\t\"\x1f\n\rCodigoRequest\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\"8\n\x10ProductoResponse\x12$\n\x08producto\x18\x01 \x01(\x0b\x32\x12.ferremas.Producto\"7\n\x0eListaProductos\x12%\n\tproductos\x18\x01 \x03(\x0b\x32\x12.ferremas.Producto2\x9e\x01\n\x0fProductoService\x12\x46\n\x0fObtenerProducto\x12\x17.ferremas.CodigoRequest\x1a\x1a.ferremas.ProductoResponse\x12\x43\n\x0fListarProductos\x12\x16.google.protobuf.Empty\x1a\x18.ferremas.ListaProductosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'productos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTO']._serialized_start=58
  _globals['_PRODUCTO']._serialized_end=147
  _globals['_CODIGOREQUEST']._serialized_start=149
  _globals['_CODIGOREQUEST']._serialized_end=180
  _globals['_PRODUCTORESPONSE']._serialized_start=182
  _globals['_PRODUCTORESPONSE']._serialized_end=238
  _globals['_LISTAPRODUCTOS']._serialized_start=240
  _globals['_LISTAPRODUCTOS']._serialized_end=295
  _globals['_PRODUCTOSERVICE']._serialized_start=298
  _globals['_PRODUCTOSERVICE']._serialized_end=456
# @@protoc_insertion_point(module_scope)
